## Functions in python

In [1]:
# Function definition
def factorial(num) :  # num - parameter
    fact = 1
    for i in range(1, num+1) :
        fact *= i
    return fact

In [2]:
var = factorial(5) # Function call
var

120

### Function Arguments

#### 1. Required Positional Argument

In [35]:
def demo(name, age) :
    print(f"Name - {name} | Age - {age}")

demo("Jane", 30)
demo(30, "Jane")  # Positional arguments
demo("Jane")   # Required Arguments

Name - Jane | Age - 30
Name - 30 | Age - Jane


TypeError: demo() missing 1 required positional argument: 'age'

In [40]:
string = "Mississippi"
string.replace("*", "i")

'Mississippi'

In [38]:
help(str.replace)

Help on method_descriptor:

replace(self, old, new, count=-1, /) unbound builtins.str method
    Return a copy with all occurrences of substring old replaced by new.

      count
        Maximum number of occurrences to replace.
        -1 (the default value) means replace all occurrences.

    If the optional argument count is given, only the first count occurrences are
    replaced.



#### 2. Default Argument

In [43]:
string = "Mississippi"
string.replace("i", "*", 2)

'M*ss*ssippi'

In [47]:
countries = {"India" : "INR", "Japan" : "Yen"}
print(countries.get("China", "no present"))

no present


In [48]:
help(countries.get)

Help on built-in function get:

get(key, default=None, /) method of builtins.dict instance
    Return the value for key if key is in the dictionary, else default.



#### 3. Variable Length Argument

In [49]:
def demo(name, *args, age = 18) :
        print(f"Name - {name} | Age - {age} | args - {args}")

demo("Jane", 80, 60, 70, 20)

Name - Jane | Age - 18 | args - (80, 60, 70, 20)


In [51]:
max(10, 20, 30, 40, 50)

50

In [52]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



#### 4. Keyword Argument

In [53]:
demo("Jane", 80, 60, 70, age = 20)

Name - Jane | Age - 20 | args - (80, 60, 70)


#### 5. Variable Length Keyword Argument

In [54]:
def demo(name, *args, age = 18, **kwargs) :
        print(f"Name - {name} | Age - {age} | args - {args} | kwargs - {kwargs}")

demo("Jane", 80, 60, 70, age = 20, gender = "f", mob = 9876543)

Name - Jane | Age - 20 | args - (80, 60, 70) | kwargs - {'gender': 'f', 'mob': 9876543}


In [55]:
help(str.maketrans)

Help on built-in function maketrans:

maketrans(...)
    Return a translation table usable for str.translate().

    If there is only one argument, it must be a dictionary mapping Unicode
    ordinals (integers) or characters to Unicode ordinals, strings or None.
    Character keys will be then converted to ordinals.
    If there are two arguments, they must be strings of equal length, and
    in the resulting dictionary, each character in x will be mapped to the
    character at the same position in y. If there is a third argument, it
    must be a string, whose characters will be mapped to None in the result.



#### Significance of `/` and `*` in function definition

- **`/`** - All the parameters before `/` must be position only
- **`*`** - All the parameters after `*` must be keyword only

In [42]:
def demo(name, age):
    print(f"Name - {name} | Age - {age}")

demo("Jane", 30) # Position only
demo(age = 30, name = "Jane")  # key-word only
demo("Jane", age = 30) # position only and keyword

Name - Jane | Age - 30
Name - Jane | Age - 30
Name - Jane | Age - 30


In [43]:
def demo(name, /, age):
    print(f"Name - {name} | Age - {age}")

demo("Jane", 30) 
demo("Jane", age = 30)
demo(age = 30, name = "Jane")  # Error

Name - Jane | Age - 30
Name - Jane | Age - 30


TypeError: demo() got some positional-only arguments passed as keyword arguments: 'name'

###### Example - str.replace()

In [44]:
help(str.replace)

Help on method_descriptor:

replace(self, old, new, count=-1, /) unbound builtins.str method
    Return a copy with all occurrences of substring old replaced by new.

      count
        Maximum number of occurrences to replace.
        -1 (the default value) means replace all occurrences.

    If the optional argument count is given, only the first count occurrences are
    replaced.



In [47]:
string = "Mississippi"
string.replace("i", "*", 2)
string.replace("i", "*", count = 2) # Error

TypeError: str.replace() takes no keyword arguments

In [48]:
def demo(name, *, age):
    print(f"Name - {name} | Age - {age}")

demo("Jane", age = 30)
demo(age = 30, name = "Jane")  
demo("Jane", 30) # Error

Name - Jane | Age - 30
Name - Jane | Age - 30


TypeError: demo() takes 1 positional argument but 2 were given

###### Example - sorted()

In [49]:
lst = [2, 3, 1, 4, 5]
sorted(lst)

[1, 2, 3, 4, 5]

In [53]:
sorted(lst, reverse=True) # DESC Order

[5, 4, 3, 2, 1]

In [50]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



#### Unpacking and packing of Tuples
- `Packing` tuples means combining multiple values into a single tuple.
- `Unpacking` a tuple means extracting the values from the tuple into individual variables.

In [3]:
tup = 1, 2, 3 # Packing of tuples
tup

(1, 2, 3)

In [5]:
a, b, c = tup  # unpacking
print(b)

2


###### Ex. Defining multiple variables in a single

In [9]:
name, age = "Jane", 30
print(f"Name - {name} | Age - {age}")

Name - Jane | Age - 30


###### Ex. Iterating overlist of tuples using for-loop

In [11]:
lst = [("Jack", 30), ("Jane", 25), ("Rosie", 34)]
for i, j in lst :
    print(i, j)

Jack 30
Jane 25
Rosie 34


In [ ]:
i = ("Jack", 30)
i, j = "Jack", 30

###### Ex. in function call

In [12]:
def cal_percentage(*marks) :
    return sum(marks)/len(marks)

In [15]:
print(f"{cal_percentage(50, 60, 70)}%")  # packing of tuples

60.0%


###### Ex. Function returning multiple values

In [17]:
def calculate(num):
    return num**2, num**3

In [18]:
calculate(5)

(25, 125)

In [20]:
square, cube = calculate(5)  # unpacking of tuples
print(square)

25


###### Ex. WAP to write data from a list to a file

In [26]:
def write_to_file(name, age, gender) :
    with open("details.txt", "a") as file : # opens file and close the file
        txt = f"{name} | {age} | {gender}\n"
        file.write(txt)
        print(f"Details of {name} added to file.")

In [24]:
data = [["Alice", 30, "Female"], ["Bob", 25, "Male"], ["Charlie", 35, "Male"], ["Diana", 28, "Female"], ["Eve", 22, "Female"]]

In [30]:
for lst in data :
    write_to_file(*lst)

Details of Alice added to file.
Details of Bob added to file.
Details of Charlie added to file.
Details of Diana added to file.
Details of Eve added to file.


In [33]:
file = open("details.txt", "r")
data = file.readlines()  # Return a list of lines from the stream.
print(data)
file.close()

['Jane | 35 | FemaleJane | 35 | Female\n', 'Jane | 35 | Female\n', 'Alice | 30 | Female\n', 'Bob | 25 | Male\n', 'Charlie | 35 | Male\n', 'Diana | 28 | Female\n', 'Eve | 22 | Female\n']


## Lambda Function

- A lambda function is also called as an anonymous function as it is a function that is defined without a name.
- A lambda function behaves similar to a standard function except it is defined in one-line.
- It is defined using a lambda key-word.
- Lambda functions can have any number of arguments but only one expression. The expression is evaluated and returned.
- Lambda functions can be used wherever function objects are required.
- Syntax of Lambda Function –

  <b>lambda *parameters* : *expression*</b>


###### Write a lambda function to return addition of 2 numbers

In [55]:
add = lambda num1, num2 : num1 + num2
add(5, 6)

11

###### Write a lambda function to return square of the number

In [56]:
sqr = lambda num1 : num1**2
sqr(7)

49

### Function Object

- Everything in Python is an object, including functions.
- You can assign them to variables, store them in data structures, and pass or return them to and from other functions
- Functions in Python can be passed as arguments to other functions, assigned to variables or even stored as elements in various data structures.


#### function definition/implemenation


In [57]:
def func(a, b):  # -> function definition
    if a < b :
        return a
    else:
        return b

#### function call

In [58]:
# function call
var = func(2, 3)
var

2

#### function object

In [59]:
# function object
var = func
var

<function __main__.func(a, b)>

In [60]:
var(2, 3)

2

In [61]:
f = len
f("abcd")

4

### Applilcations of Function Object

###### Ex. WAP to sort a list of strings as per the last character.

In [62]:
lst = ["train", "car", "flight", "bike"]
sorted(lst) # sorts as per the alphabetical order

['bike', 'car', 'flight', 'train']

In [63]:
sorted(lst, key = len) # sorts as per the len of each word

['car', 'bike', 'train', 'flight']

In [64]:
sorted(lst, key = lambda strg : strg[-1]) # sorts as per the last character of each word

['bike', 'train', 'car', 'flight']

In [68]:
min("car")

'a'

In [65]:
max(lst)

'train'

In [66]:
max(lst, key = len)

'flight'

In [67]:
min(lst, key = len)

'car'

In [69]:
max(lst, key = min)

'flight'

##### Note - 
- A lambda function creates a function object, so we need to assign it to a variable to invoke the function.
- It is used as a function object when the function's code can be expressed in a single line.

###### Ex. WAP to display the student details in sorted order of their marks.

In [70]:
students = {"Jane" : 40, "Max" : 50, "Sam" : 45, "Mary" : 70}
students.items()

dict_items([('Jane', 40), ('Max', 50), ('Sam', 45), ('Mary', 70)])

In [71]:
sorted(students.items()) # Returns a list object

[('Jane', 40), ('Mary', 70), ('Max', 50), ('Sam', 45)]

In [72]:
# convert the output of sorted to a dict - 
dict(sorted(students.items()))  # dict in sorted order of name

{'Jane': 40, 'Mary': 70, 'Max': 50, 'Sam': 45}

In [76]:
# Sort the dict in DES`C order of marks - 
dict(sorted(students.items(), key = lambda tup : tup[1], reverse=True))

{'Mary': 70, 'Max': 50, 'Sam': 45, 'Jane': 40}

In [83]:
key = lambda tup : tup[1]
for i in students.items():
    print(key(i))

40
50
45
70


<hr><hr>

## Exception Handling

It may be convenient to recognize the problems in your python code before you put it to real use. But that does not always happen. Sometimes, problems show up when you run the code; sometimes, midway of that. A Python exception is an error that's detected during execution.

##### Python does not provide any compile time Exception Handling. Developer has to proactively recognize the need for exception handling.

- What are Errors and Exceptions
- Handling Exceptions
- Defining Clean-up Actions
- Predefined Clean-up Actions
- Raising Exceptions

### Syntax Error

In [84]:
for i in range(5)
   print(i)

SyntaxError: expected ':' (694265647.py, line 1)

In [85]:
print("Hello"

SyntaxError: incomplete input (1647630127.py, line 1)

In [86]:
print("Hello')

SyntaxError: unterminated string literal (detected at line 1) (2084448154.py, line 1)

In [88]:
for i in range(5) :
print(i)

IndentationError: expected an indented block after 'for' statement on line 1 (4120667250.py, line 2)

### Exception
Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it. Errors detected during execution are called exceptions and are not unconditionally fatal

#### ZeroDivisionError

In [91]:
a, b = 1, 0
print(a/b)

ZeroDivisionError: division by zero

#### ValueError

In [94]:
int("abcd")

ValueError: invalid literal for int() with base 10: 'abcd'

#### NameError

In [96]:
Z = 1
print(z)

NameError: name 'z' is not defined

#### FileNotFoundError

In [97]:
open("abc.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'abc.txt'

#### TypeError

In [98]:
"2" + 2

TypeError: can only concatenate str (not "int") to str

In [103]:
def func(a):
    pass

func()

TypeError: func() missing 1 required positional argument: 'a'

#### IndexError

In [101]:
lst = [1,2,3]
lst[10]

IndexError: list index out of range

#### KeyError

In [104]:
d = {1:2, 3:4}

d["abc"]

KeyError: 'abc'

#### ModuleNotFoundError

In [105]:
import math1

ModuleNotFoundError: No module named 'math1'

#### AttributeError

In [106]:
import math
math.sq1()

AttributeError: module 'math' has no attribute 'sq1'

In [107]:
string = "abcd"

string.UPPER()

AttributeError: 'str' object has no attribute 'UPPER'

### Handling Exceptions

In [110]:
try :
    num = int(input("Enter a number - "))
    den = int(input("Enter a number - "))
    print(num/den)
except ZeroDivisionError as err:
    print("Denominator is zero")
print("Continuing the rest of the program ------ ")

Enter a number -  10
Enter a number -  0


Denominator is zero
Continuing the rest of the program ------ 


In [112]:
num = int(input("Enter a number - "))
den = int(input("Enter a number - "))
print(num/den)
print("Continuing the rest of the program ------ ")

Enter a number -  10
Enter a number -  0


ZeroDivisionError: division by zero

### Rasie an Exception

In [127]:
# Using try-except block for validating inputs - 
def take_input():
    try : 
        x = int(input("Enter a number in the range of 0-9 - "))  # Value Error
        if x in range(0, 10) :
            return x
        raise TypeError("Number must be in the range of 0-9.")
    except ValueError as e:
        print(e, " - Value error")
        return take_input()
    except Exception as e :
        print(e, "- Exception block")
        return take_input()

# Main Program - take int number in the range of 0-9
num = take_input()
print(num * 100)

Enter a number in the range of 0-9 -  abcd


invalid literal for int() with base 10: 'abcd'  - Value error


Enter a number in the range of 0-9 -  20


Number must be in the range of 0-9. - Exception block


Enter a number in the range of 0-9 -  5


500


In [123]:
def factorial(num) :
    if type(num) == int :
        fact = 1
        for i in range(1, num+1) :
            fact *= i
        return fact
    else :
        raise Exception("Invalid Argument.")

In [124]:
factorial(1.5)

Exception: Invalid Argument.

<hr><hr>

## Object Oriented Programming

1. **Classes and Objects**: Classes are blueprints for creating objects. Objects are instances of classes. Each object can have attributes (variables) and methods (functions).

2. **Constructors**: Constructors (`__init__`) are special methods that are automatically called when an object is created.

3. **Self Parameter**: The `self` parameter is a reference to the current instance of the class. It is used to access variables and methods of the class.

4. **Encapsulation**: This principle involves bundling the data (attributes) and the methods (functions) that operate on the data into a single unit or class. Access to the data is restricted to specific methods.

5. **Inheritance**: Inheritance allows a new class (subclass) to inherit attributes and methods from an existing class (superclass). This helps in reusing and extending existing code.

6. **Polymorphism**: Polymorphism means "many forms". It allows methods to do different things based on the object it is acting upon. This can be achieved through method overriding.

7. **Abstraction**: Abstraction means hiding the complex implementation details and showing only the necessary features of an object. This is achieved using abstract classes and interfaces.

8. **Special Methods**: These methods have double underscores before and after their names (e.g., `__str__`, `__repr__`, `__len__`). They are also known as "dunder" methods and are used for operator overloading and providing custom behavior for built-in functions.

###### Ex. Design an application where users can select a shape from available options, input the dimensions, and choose a color. The application will calculate and provide the cost of painting the selected shape based on the given dimensions and color.
- Application must be scalable - we should be able to add a new shape
- Add new colors and modify cost calculation without affecting previous algorithm

In [160]:
class Circle :

    # Constructor
    def __init__(self, radius) :
        self.__radius = radius    # self.radius - instance variable and radius - local variable
        self.cal_area()
# self.__radius - private variable cannot be modified outside the class

    def cal_area(self):  # instance method
        self.area = 3.14 * (self.__radius ** 2)

In [156]:
c1 = Circle(10)
c1.area

314.0

In [158]:
c2 = Circle(20)
c2.area

1256.0

In [161]:
c2 = Circle(30)
c2.area

2826.0

In [162]:
print(dir(Circle))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cal_area']


In [163]:
print(dir(str))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [164]:
print(dir(__builtin__))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BaseExceptionGroup', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EncodingWarning', 'EnvironmentError', 'Exception', 'ExceptionGroup', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'S

In [165]:
import math
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [190]:
from abc import ABC, abstractmethod
class Shape(ABC):
    prices_dict = {"white" : 1, "red" : 10, "blue" : 15, "green" : 20}  # class variable
    def __init__(self):
        self.area = 0

    @abstractmethod
    def cal_area(self):
        pass

    def cost(self, color = None) :
        price = Shape.prices_dict.get(color, 1)
        return self.area * price

class Circle(Shape) :  # Inheritance
    
    def __init__(self, radius) :
        self.radius = radius  
        self.cal_area()

    def cal_area(self):
        self.area = 3.14 * (self.radius ** 2)

class Rectangle(Shape) :
    def __init__(self, length, breadth):
        self.length = length
        self.breadth = breadth

    def area(self) :
        self.area = self.length * self.breadth

In [172]:
c1 = Circle(10)
c1.cost("red")

3140.0

In [181]:
r1 = Rectangle(10, 200)
r1.cost("red")

20000

In [187]:
shapes = [Circle(10), Circle(20), Rectangle(10, 20), Rectangle(20, 30)]
for s in shapes :
    s.area()
    print(s.cost("red"))

TypeError: 'float' object is not callable

ABC - Abstract Base Class - This will mark the Shape class as abstract and will not alllow creation of shape object

In [191]:
s1 = Shape()

TypeError: Can't instantiate abstract class Shape without an implementation for abstract method 'cal_area'

In [192]:
r1 = Rectangle(10, 20)

TypeError: Can't instantiate abstract class Rectangle without an implementation for abstract method 'cal_area'

In [194]:
c1 = Circle(5)

In [208]:
from abc import ABC, abstractmethod
class Shape(ABC):
    prices_dict = {"white" : 1, "red" : 10, "blue" : 15, "green" : 20}  # class variable
    def __init__(self, color = None):
        self.cal_area()   
        self.color = color

    @abstractmethod
    def cal_area(self):
        pass

    def cost(self, color = None) :
        if self.color : 
            color_picked = self.color
        else:
            color_picked = color
            
        price = Shape.prices_dict.get(color_picked, 0)            
        return f"{self.area * price} - color chosen is {color_picked}"

class Circle(Shape) :  # Inheritance
    
    def __init__(self, radius, color = None) :
        self.radius = radius  
        super().__init__(color)

    def cal_area(self):
        self.area = 3.14 * (self.radius ** 2)

class Rectangle(Shape) :
    def __init__(self, length, breadth):
        self.length = length
        self.breadth = breadth
        super().__init__()

    def cal_area(self) :
        self.area = self.length * self.breadth

In [210]:
shapes = [Circle(10, "blue"), Circle(20), Rectangle(10, 20), Rectangle(20, 30)]
for s in shapes :
    print(s.cost("red"))

4710.0 - color chosen is blue
12560.0 - color chosen is red
2000 - color chosen is red
6000 - color chosen is red


<hr><hr>

## Basics of NumPy
- NumPy - Introduction and Installation
- NumPy - Arrays Data Structure ( 1D, 2D, ND arrays)
- Creating Arrays
- NumPy - Data Types
- Array Attributes
- Creating Arrays – Alternative Ways
- Sub-setting, Slicing and Indexing Arrays
- Operations on Arrays
- Array Manipulation


### NumPy – Introduction and Installation

- NumPy stands for ‘Numeric Python’
- Used for mathematical and scientific computations
- NumPy array is the most widely used object of the NumPy library

#### Installing numpy

!pip install numpy

#### Importing numpy

In [1]:
import numpy as np  # has numric functionalities
import pandas as pd  # data manipulation
import matplotlib.pyplot as plt  # basic data visuzlisation
import seaborn as sns # advanced data visualisation
print("All imported")

All imported


In [ ]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn

### Arrays Data Structure

An `Array` is combination of homogenous data objects and can be indexed across multiple dimensions

#### Arrays are –
- ordered sequence/collection of Homogenous data
- multidimensional
- mutable


#### Creating Arrays – From list/tuple

- `np.array()` is used to create a numpy array from a list


#### Example on 1-D Array

In [215]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

#### Example on 2-D Array

In [216]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [220]:
np.array([[1,3],[5,6]])

array([[1, 3],
       [5, 6]])

#### Array Attributes

- Attributes are the features/characteristics of an object that describes the object

- Some of the attributes of the numpy array are:
    - **shape** - Array dimensions
    - **size** - Number of array elements
    - **dtype** - Data type of array elements
    - **ndim** - Number of array dimensions
    - **dtype.name** - Name of data type
    - **astype** - Convert an array to a different type


In [217]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [218]:
arr.shape

(3, 4)

In [221]:
arr.size

12

In [222]:
arr.ndim

2

In [223]:
arr.dtype

dtype('int64')

In [224]:
arr.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

#### Examples -

In [2]:
coffee_products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array( [52248.7, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])
target_profits = np.array([15934.0, 4924.0, 31814.0, 19649.0, 24934.0, 8461.0, 7090.0, 7084.0, 10135.0, 16306.0])
target_sales = np.array([48909.0, 13070.0, 80916.0, 57368.0, 66906.0, 30402.0, 18212.0, 21628.0, 27336.0, 42102.0])

###### Ex. How many products are there in the dataset?

In [226]:
coffee_products.size

10

###### Ex.  Sales greater than 50,000

In [227]:
sales > 50000  # Returns a boolean array

array([ True, False,  True,  True,  True, False, False, False, False,
       False])

In [230]:
sales[sales > 50000]  # Conditional indexing

array([52248.7, 71060. , 60014. , 69925. ])

###### Ex.  Identify Losses

In [232]:
profits[profits < 0]

array([-2954.])

###### Ex.  Products in loss

In [233]:
coffee_products[profits < 0]

array(['Green Tea'], dtype='<U17')

###### Ex.  Product with maximum Sales

In [252]:
coffee_products[sales == np.max(sales)]

array(['Colombian'], dtype='<U17')

In [249]:
np.max(sales)

np.float64(71060.0)

In [250]:
np.argmax(sales)

np.int64(2)

In [251]:
coffee_products[np.argmax(sales)]  # Indexing 

np.str_('Colombian')

###### Ex. Apply 7% service tax to sales

In [255]:
np.round(sales * 1.07, 1)  # Array and scaler

array([55906.1, 15052.8, 76034.2, 64215. , 74819.8, 29650.8, 20577.2,
       26614.1, 35122.8, 47196.6])

###### Ex. Calculate Profit ratio for each product

In [257]:
# Array and array operation
np.round(profits / sales, 2)

array([ 0.33,  0.36,  0.4 ,  0.34,  0.34,  0.28, -0.15,  0.29,  0.33,
        0.34])

In [260]:
ratio = profits / sales
np.round(ratio, 4) * 100

array([ 33.39,  35.83,  39.95,  34.09,  33.51,  27.75, -15.36,  28.78,
        32.66,  33.78])

###### Ex. Identify the products meeting the Target Profits

In [278]:
profit_ach = coffee_products[profits >= target_profits]
print(profit_ach)

['Caffe Latte' 'Cappuccino' 'Darjeeling' 'Lemon' 'Mint']


In [277]:
list(profit_ach) # to convert to list

[np.str_('Caffe Latte'),
 np.str_('Cappuccino'),
 np.str_('Darjeeling'),
 np.str_('Lemon'),
 np.str_('Mint')]

In [276]:
",".join(profit_ach).split(",")  # Convert to list as str object and not as a np.str_ object

['Caffe Latte', 'Cappuccino', 'Darjeeling', 'Lemon', 'Mint']

###### Ex. Are the above products meeting their sales target too?

In [285]:
sales_ach = coffee_products[sales > target_sales]
sales_ach

array(['Caffe Latte', 'Cappuccino', 'Darjeeling', 'Decaf Irish Cream',
       'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'], dtype='<U17')

In [288]:
np.isin(profit_ach, sales_ach)  # Checks if each element of arr1 in arr2 and returns bool array

array([ True,  True,  True,  True,  True])

In [289]:
np.all(np.isin(profit_ach, sales_ach)) # Returns True if all values are True

np.True_

###### Ex. Identify products meeting sales targets but not profit targets

In [291]:
np.all(np.isin(sales_ach, profit_ach))

np.False_

In [292]:
np.setdiff1d(sales_ach, profit_ach)  # Products achieving sales target but not profit target

array(['Decaf Irish Cream', 'Green Tea', 'Regular Espresso'], dtype='<U17')

###### Ex. Identify the products that are not meeting their profit targets and list them in descending order based on their percentage target achievement.
1. Identify all the products failing to meet profit targets.
2. Calculate the percentage of target achievement.
3. Display them in descending order of percentage value.

In [5]:
off_products = coffee_products[profits < target_profits]
off_profits = profits[profits < target_profits]
off_targets = target_profits[profits < target_profits]
percentage = np.round(off_profits / off_targets * 100, 2)
percentage

array([ 89.24,  93.98,  90.9 , -41.66,  91.39])

In [7]:
# Replace negative values with zero
percentage[percentage < 0] = 0
percentage

array([89.24, 93.98, 90.9 ,  0.  , 91.39])

In [11]:
# Sorting Arrays
# option 1 - will sort the selected array and returns a new array in ASC order
np.sort(percentage)[::-1] # Sorts DESC - [::-1]

array([93.98, 91.39, 90.9 , 89.24,  0.  ])

In [14]:
# Option 2 - use np.argsort() to generate a sort order and apply it to all the arrays
sort_order = np.argsort(percentage)[::-1]
sort_order

array([1, 4, 2, 0, 3])

In [15]:
for product, percent in zip(off_products[sort_order], percentage[sort_order]):
    print(f"{product} has achieved {")

array(['Decaf Irish Cream', 'Regular Espresso', 'Earl Grey', 'Colombian',
       'Green Tea'], dtype='<U17')

array([93.98, 91.39, 90.9 , 89.24,  0.  ])

#### Ex. Appending arrays

In [241]:
arr1 = np.array([[2, 3], [4, 5], [6, 7]])
arr1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [240]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [ ]:
np.append(arr1, arr2.reshape(4, 2), axis = 0)

array([[2, 3],
       [4, 5],
       [6, 7],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [244]:
np.append(arr1, arr2).reshape(7, 2)

array([[2, 3],
       [4, 5],
       [6, 7],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])